### ISSUE TITLE
Consistently reports 0 W for DRAM consumption

### ISSUE THREAD

**Issue by wanecek** [hubblo-org/scaphandre#108]
## Bug description

Scaphandre reports 0 W as the DRAM consumption.

## Expected behavior

I hoped scaphandre would include DRAM measurements.

## Screenshots

![Screenshot-2021-05-07T09:09:55](https://user-images.githubusercontent.com/1533747/117412359-00f28580-af15-11eb-8ce1-3866d8fa5652.png)

![Screenshot-2021-05-07T09:27:00](https://user-images.githubusercontent.com/1533747/117413587-71e66d00-af16-11eb-9040-1c58ec43860f.png)

## Environment

- **Linux distribution version**: Ubuntu 20.04.2
- **Kernel version**: 5.4.0-67-generic
- **CPU:** Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
- **Scaphandre version:** `a7b0159ce5135e2b25fe4c97a86434d30f6e0982` (self-built). Also tried pre-built docker image.

## Additional context

I realize that this may very well be the intended behavior, and not a bug (e.g. because the Intel RAPL sensor or powercap doesn't output RAM for this CPU make). I was mainly hoping to get clarifications into this - if it's something I will be able to fix (maybe I'm just operating scaphandre wrong or am missing something silly?), or if it's just the way it is. Thank you for having written this really useful tool!

Also, could it simply be because the memory usage is low, i.e. around 1GB used with 11GB buff/cached?

```bash
root@Ubuntu-2004-focal-64-minimal ~ # free -m
              total        used        free      shared  buff/cache   available
Mem:          31900        1381       19428         140       11090       29945
Swap:         16366           0       16366
```

**Comment by wanecek** [comment]
From reading other issues and how they're debugged, _maybe_ this is useful? Sorry, I know very little about Powercap :sweat_smile: 

```bash
root@Ubuntu-2004-focal-64-minimal ~ # ls /sys/class/powercap/
intel-rapl  intel-rapl:0  intel-rapl:0:0  intel-rapl:0:1  intel-rapl:0:2
```

```bash
root@Ubuntu-2004-focal-64-minimal ~ # ls /sys/class/powercap/intel-rapl:0:2
constraint_0_max_power_uw    device               name
constraint_0_name            enabled              power
constraint_0_power_limit_uw  energy_uj            subsystem
constraint_0_time_window_us  max_energy_range_uj  uevent
```

```bash
root@Ubuntu-2004-focal-64-minimal /sys/class/powercap/intel-rapl:0:2 # cat energy_uj
185204869380
```

**Comment by bpetit** [comment]
Hi !

Thanks for reporting that. Could you confirm that /sys/class/powercap/intel-rapl:0:2/name contains "dram" ?

What's strange too is that the sum of "core" and "uncore" power consumption is above the total power consumption of the host. I couldn't reproduce it on the machines I have access to. We could have diverse behaviour depending on the hardware and the kernel version. We will surely have to ask you to run some tests to work on it.

I've added this issue to the global board, I'd prefer someone else to look at it but I'll do it if nothing has moved in a few time.

**Comment by wanecek** [comment]
Hi @bpetit, thank you for your quick and kin reply! Yeah, indeed, the sums not adding up is strange, now that you mention it... 

I can confirm that the `name` contains (or equals) "dram". Just let me know if there's any more information that I can provide to help you debug, or if there's any specific place I should start when debugging. I started trying to debug the issue, but didn't get very far. Will try some more later this week.

```bash
root@Ubuntu-2004-focal-64-minimal ~ # cat /sys/class/powercap/intel-rapl:0:2/name
dram
```

**Comment by wanecek** [comment]
Update: I discovered [powerapi-ng/energy-scripts](https://github.com/powerapi-ng/energy-scripts/) today, which seems to be a shell script reading from the powercap sensor. I was able to have it report DRAM data back to me, suggesting that at least my sensor is able to report data on the dram usage (unless the energy-scripts file is lying to me, haha!)

**Comment by wanecek** [comment]
I'm continuing my futile attempts to debug this. 

When trying to log what the path to the counter_uj_path for sockets are, I get that only one socket is created (and iterated over), and the path to its energy counter uj file is `/sys/class/powercap/intel-rapl:0/energy_uj`. Should there be a separate socket for dram (i.e. pointing to `intel-rapl:0:2/` instead of `intel-rapl:0/`?

```diff
diff --git a/src/exporters/stdout.rs b/src/exporters/stdout.rs
index e22efb3..52265f1 100644
--- a/src/exporters/stdout.rs
+++ b/src/exporters/stdout.rs
@@ -99,6 +99,10 @@ impl StdoutExporter {

     fn iterate(&mut self) {
         self.topology.refresh();
+        println!("We have {} sockets", &self.topology.sockets.len());
+        for s in &self.topology.sockets {
+            println!("{}: path was {}", s.id.to_string(), s.counter_uj_path);
+        }
         self.show_metrics();
     }

diff --git a/src/sensors/mod.rs b/src/sensors/mod.rs
index 32fbcdc..69cca6c 100644
--- a/src/sensors/mod.rs
+++ b/src/sensors/mod.rs
@@ -609,6 +609,7 @@ impl CPUSocket {
         counter_uj_path: String,
         buffer_max_kbytes: u16,
     ) -> CPUSocket {
+        println!("Created socket with path: {}", counter_uj_path);
         CPUSocket {
             id,
             domains,
```

**Comment by wanecek** [comment]
I think the above is even clearer in the json exporter, where we on one hand have a hard-coded names array (https://github.com/hubblo-org/scaphandre/blob/main/src/exporters/json.rs#L166), but when logging the domain name (instead of using the array), I get the following:

```
Domain.name is dram, but names[index] is core
Domain.name is core, but names[index] is uncore
Domain.name is uncore, but names[index] is dram
```

```diff
diff --git a/src/exporters/json.rs b/src/exporters/json.rs
index a6a3ca3..4a3a68e 100644
--- a/src/exporters/json.rs
+++ b/src/exporters/json.rs
@@ -177,12 +177,17 @@ impl JSONExporter {
                 let domains = socket
                     .get_domains_passive()
                     .iter()
-                    .map(|d| d.get_records_diff_power_microwatts())
+                    .enumerate()
+                    .map(|(index, d)| {
+                        println!("Domain.name is {}, but names[index] is {}", d.name, names[index]);
+                        return d.get_records_diff_power_microwatts();
+                    })
                     .map(|record| record.map(|d| d.value))
                     .enumerate()
                     .map(|(index, d)| {
                         let domain_power =
                             d.map(|value| value.parse::<u64>().unwrap()).unwrap_or(0);
+
                         Domain {
                             name: names[index].to_string(),
                             consumption: domain_power as f32,
``

**Comment by PierreRust** [comment]
Hi, 
I just had a look and there is indeed the way the stdout exported prints out the results, the order of domains is assumed to be `[Core, Uncore, DRAM]`which is not necessarily the case. It's probably the same with json, I have not checked yet.

I'll try to push a PR.

**Comment by wanecek** [comment]
Great, thanks!

Yeah, I tried sorting the array inside powercap_rapl.rs, as below, and am now getting DRAM results on both json and stdout exporter (forgive the probably horrendously unsemantic rust):

```diff
diff --git a/src/sensors/powercap_rapl.rs b/src/sensors/powercap_rapl.rs
index 208b420..e57eb35 100644
--- a/src/sensors/powercap_rapl.rs
+++ b/src/sensors/powercap_rapl.rs
@@ -73,8 +73,17 @@ impl Sensor for PowercapRAPLSensor {
         }
         let mut topo = Topology::new();
         let re_domain = Regex::new(r"^.*/intel-rapl:\d+:\d+$").unwrap();
-        for folder in fs::read_dir(&self.base_path).unwrap() {
-            let folder_name = String::from(folder.unwrap().path().to_str().unwrap());
+
+        let mut folder_names = fs::read_dir(&self.base_path)
+            .unwrap()
+            .map(|folder|
+                String::from(folder.unwrap().path().to_str().unwrap())
+            )
+            .collect::<Vec<_>>();
```

**Comment by bpetit** [comment]
Well done ! Looks like a bug solved ! :)
