### ISSUE TITLE
Survey on globally distributed software engineering 

### ISSUE THREAD

**Issue by AsWali** [hubblo-org/scaphandre#110]
Hey there. 

We are doing a survey on globally distributed software engineering focused on open source projects. If you have some spare time we would really appreciate your response. The form takes about 10 minutes. Thanks in advance!
Survey can be found [here](https://forms.gle/N1TnifRuCYHrCY9JA)

**Comment by bpetit** [comment]
Hi,

Please spread your survey by other means than using issues for this. I'm closing this issue, this is not against your initiative, but I don't think this is the place for it.
