### ISSUE TITLE
Add Cargo.lock to the repository

### ISSUE THREAD

**Issue by mmai** [hubblo-org/scaphandre#111]
## Bug description

The _Cargo.lock_ file is currently ignored.  _scaphandre_ being an executable, I think it should not be ignored, as stated in the comment of the .gitignore.

## To Reproduce

Check that there is no _Cargo.lock_ file in the repository, .

## Expected behavior

There should be a _Cargo.lock_ file, and the _.gitignore_ file should not contain 'Cargo.lock'

## Environment

All

## Additional context

I stumbled on this little problem when writing a Nixos flake to package Scaphandre :  
``` 
  ERROR: The Cargo.lock file doesn't exist

  Cargo.lock is needed to make sure that cargoHash/cargoSha256 doesn't change
  when the registry is updated.
```

**Comment by bpetit** [comment]
Done !

**Comment by uggla** [comment]
This is strange as most of the other Rust project does not include the Cargo.lock. I checked several of them.
So I'm not sure having it in the repo is a good idea.

**Comment by uggla** [comment]
Looking at the doc, yep finally binaries should include Cargo.lock : https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

**Comment by mmai** [comment]
Thanks!  I could complete my package. Flakes are still an experimental feature of Nix, but I've published it [here](https://github.com/mmai/scaphandre-flake) if you're interested.

**Comment by bpetit** [comment]
Thank you for creating the package ! :)
