### ISSUE TITLE
Install Scaphandre with Helm

### ISSUE THREAD

**Issue by MaximeAlten** [hubblo-org/scaphandre#122]
Hello !
## Bug description

Using the official repository "stable" but can't get scaphandre on it :
Error: failed to download "stable/scaphandre" (hint: running `helm repo update` may help)

## To Reproduce

Using commande line :
helm install scaphandre helm/scaphandre or helm install scaphandre stable/scaphandre

## Expected behavior

Installation of scaphandre

## Environment

- Linux distribution version CentOS 8.4
- Kernel version : 4.18.0-305.12.1.el8_4.x86_64

Thanks for your help

**Comment by MaximeAlten** [comment]
Hello,
Any news for this please?
Thanks for your time,
Maxime

**Comment by bpetit** [comment]
Hi,

I think the chart has not been pushed to any helm repository yet.

The only way to use it is to call the local chart folder. Could you provide the output of the `helm install scaphandre helm/scaphandre` command instead please ?

Thanks

**Comment by MaximeAlten** [comment]
Hello,
You're right. We just "debugged" it. It is because I didn't make a gitclone first.
That's on me!
Thanks for your time
