### ISSUE TITLE
[helm] support for the `--vm` option in the command line of the pods

### ISSUE THREAD

**Issue by arthurlogilab** [hubblo-org/scaphandre#138]
## Bug description

With the current helm chart, one can only deploy to kubernetes with "baremetal" server (from my understanding). Adding the `--vm` option *before* `prometheus` argument  can't be done with the `extraArgs` in the `values.yaml`. 

## To Reproduce

Deploy with helm on a kubernetes cluster that uses VMs. 

## Expected behavior

Here is what I had to add to the daemonset : 

```
diff --git a/helm/scaphandre/templates/daemonset.yaml b/helm/scaphandre/templates/daemonset.yaml
index d88b540..f37050b 100644
--- a/helm/scaphandre/templates/daemonset.yaml
+++ b/helm/scaphandre/templates/daemonset.yaml
@@ -20,6 +20,7 @@ spec:
       - name:  {{ template "scaphandre.name" . }}
         image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
         args:
+            - --vm
             - {{ .Values.scaphandre.command }}
             {{- range $key, $value := .Values.scaphandre.extraArgs }}
             {{- if $value }}
```

This should probably be templated and be an option the `values.yaml`

An alternative would be for the `scaphandre` command to accept the `--vm` option also after the `prometheus` argument / command. 

## Environment

- Linux distribution version : n/a
- Kernel version (output of `uname -r`): n/a

**Comment by jotak** [comment]
this should fix it: https://github.com/hubblo-org/scaphandre/pull/139

**Comment by bpetit** [comment]
#139 is merged. Could you tell us if that fits your need or not @arthurlogilab ?

Thanks, both of you !

**Comment by arthurlogilab** [comment]
Looks great thank!

**Comment by bpetit** [comment]
Thank you !
