### ISSUE TITLE
CPU percentage usage per process

### ISSUE THREAD

**Issue by STandon-3** [hubblo-org/scaphandre#141]
## Problem
I'd like Scaphandre to be able to export a metric for the CPU percentage usage for every process, and not just the Scaphandre process.
In particular, I'm trying to get the CPU percentage usage for each virtual machine running on a server.

## Solution

I can see that there is a get_process_cpu_consumption_percentage [function](https://github.com/hubblo-org/scaphandre/blob/6a7350fa41ad6ef4e5098c943d0d14ea973da89a/src/sensors/mod.rs#L516-L541) to calculate this in the code, which I believe is used to provide the `scaph_self_cpu_usage_percent` metric (the CPU usage of the Scaphandre process itself).
Could this same function be used to calculate metrics for other processes and exposed in the exporters?

## Alternatives

I'm aware that this could also possibly be calculated using the stats from [node_exporter](https://github.com/prometheus/node_exporter) or with the [libvirtd exporter](https://github.com/vexxhost/libvirtd_exporter) for virtual machines in particular, but it would be good to use Scaphandre so that the CPU usage calculation was the same as that used for the `scaph_process_power_consumption_microwatts`.
Alternatively, it's probably possible to reverse engineer using `scaph_process_power_consumption_microwatts` and `scaph_host_power_microwatts`, although a little inconvenient!

**Comment by bpetit** [comment]
This has been implemented in https://github.com/hubblo-org/scaphandre/pull/274 as scaph_process_cpu_usage_percentage metric.

This is currently in dev. Documentation is not ready yet but will be for 1.0 release (next one).

I'd love to have your feedbacks on this once it's in dev :)
