### ISSUE TITLE
Scaphandre - Throwing error with AWS EC2 instance

### ISSUE THREAD

**Issue by liz-george** [hubblo-org/scaphandre#142]
## Bug description

I am trying to run the Scaphandre tool on my server. However it throwing the panic error.

Error : 

Input : docker run -v /sys/class/powercap:/sys/class/powercap -v /proc:/proc -ti hubblo/scaphandre stdout -t 15

Output : 
thread 'main' panicked at 'Trick: if you are running on a vm, do not forget to use --vm parameter invoking scaphandre at the command line', src/sensors/mod.rs:263:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

## To Reproduce

- Refer the documentation : https://hubblo-org.github.io/scaphandre-documentation/tutorials/quickstart.html
- modprobe intel_rapl_common
- docker run -v /sys/class/powercap:/sys/class/powercap -v /proc:/proc -ti hubblo/scaphandre stdout -t 15

## Expected behavior

 docker run -v /sys/class/powercap:/sys/class/powercap -v /proc:/proc -ti hubblo/scaphandre stdout -t 15

I am able to run locally on my system and get the output. Please see the screenshot for reference.

## Screenshots

![Screenshot from 2021-12-10 14-17-18](https://user-images.githubusercontent.com/67887994/145545343-371854cf-2feb-41a5-af0f-be1dac0acfe0.png)

## Environment

- AWS EC2 instance (Ubuntu 20.04.3 LTS (GNU/Linux 5.15.6-051506-generic x86_64))
- Kernel version - 5.15.6-051506-generic

This tool will work perfect for my project. Please let me know if i missed anything,
Thanks a bunch!

**Comment by demeringo** [comment]
Hi Liz, for the time being Scaphandre does not support EC2 instances.

The reason being that public cloud providers do not expose the underlying RAPL sensors that scaphandre and other measurment tools rely on to track consumption.

This is likely the reason of the panick.

See https://github.com/hubblo-org/scaphandre/issues/25.

The only alternative I am aware of rely on estimating the consumption with method like this:
https://medium.com/teads-engineering/estimating-aws-ec2-instances-power-consumption-c9745e347959
https://medium.com/teads-engineering/building-an-aws-ec2-carbon-emissions-dataset-3f0fd76c98ac

**Comment by liz-george** [comment]
> Hi Liz, for the time being Scaphandre does not support EC2 instances.
> 
> The reason being that public cloud providers do not expose the underlying RAPL sensors that scaphandre and other measurment tools rely on to track consumption.
> 
> This is likely the reason of the panick.
> 
> See #25.
> 
> The only alternative I am aware of rely on estimating the consumption with method like this: https://medium.com/teads-engineering/estimating-aws-ec2-instances-power-consumption-c9745e347959 https://medium.com/teads-engineering/building-an-aws-ec2-carbon-emissions-dataset-3f0fd76c98ac

Thank you for your response.
