### ISSUE TITLE
Push a versioned tag of the docker image when new Scaphandre releases are created

### ISSUE THREAD

**Issue by rossf7** [hubblo-org/scaphandre#152]
## Problem

I would like to use a tagged version of the docker image instead of the latest tag. So the version of scaphandre is predictable.

## Solution

This can be automated using the docker [build-push-action](https://github.com/docker/build-push-action). This will push a new tag to docker hub when a new git tag is created.

This can be combined with the docker [metadata-action](https://github.com/docker/metadata-action) which will set the latest tag according to semver and add some useful labels to the docker image.

I tried this out in my fork and it seems to work well. I just needed to disable the push step because secrets aren't passed for forked repos. Here is the [action](https://github.com/rossf7/scaphandre/blob/bba54670f7cb2154b907c7607a75dfb553c9acad/.github/workflows/docker-release.yml) and an example [run](https://github.com/rossf7/scaphandre/runs/4685826904?check_suite_focus=true). 

## Alternatives

Pushing the image can be done many ways but I like the idea of using these actions since they are maintained by Docker.

**Comment by demeringo** [comment]
What _I_ would like to see (does not means it is the right thing to do ;-) ) is getting access to both a stable (released) and unstable version (dev).

- The _stable_ version could be tagged as `latest` + `vX.X.X` (i.e. the git tag, as suggested by @rossf7).
- The _unstable_ (or _testing_ or _development_) version would be based on _dev_branch.

Idea is to permit easy integration or testing of the latest functionalities (by requesting docker hub for the `:dev` tag)  while keeping the possibility to use the _stable_  release in the general case (using either the `:latest` or `:vx.x.x` tags).

Does this sounds right to you ?

**Comment by rossf7** [comment]
@demeringo thanks I like the idea as it would be useful for testing the latest functionality.

It should be possible with a simple change to the github action. I'll give it a try and let you know how it goes.

```
on:
  push:
    branches:
      - 'dev'
    tags:
      - 'v*.*.*'
```

**Comment by rossf7** [comment]
@demeringo yes it works it just needs a small change to the docker-metadata action.

```
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
```

@bpetit What do you think to setting up this tagging?

**Comment by demeringo** [comment]
@rossf7 @bpetit I realize that if we publish multiple images, we may also need to update doc. To explain which image should be preferabily used. I can handle this on a separate PR.

**Comment by bpetit** [comment]
This would be great. Moreover, w'ell need different tags to provide scaphandre built with different features or sensors. 

Feel free to bootstrap that in PRs, and thanks a lot.

The tagging pattern you proposed suits me well !

**Comment by rossf7** [comment]
I opened https://github.com/hubblo-org/scaphandre/pull/160 to add the action.

**Comment by bpetit** [comment]
works !

Thanks !

![Capture d’écran du 2022-06-15 11-27-12](https://user-images.githubusercontent.com/906428/173794101-d67ab6c3-59ef-463f-9706-58a13aa7207a.png)

**Comment by rossf7** [comment]
Thx! @bpetit <3
