### ISSUE TITLE
How exactly is the energy usage attributed to each individual process?

### ISSUE THREAD

**Issue by vaastav** [hubblo-org/scaphandre#156]
I am curious as to how the energy usage is attributed to each individual process. The reason I ask is that I would like to have fine-grained energy measurements of snippets of code running in a given process. I am curious as to how that would be possible with scaphandre.

**Comment by mrchrisadams** [comment]
Hi @vaastav  does this shed any light? I had this same question, and I tried  to write it up myself after speaking to Benoit and carefully reading the code a while back (not so easy if you're not fluent in rust…)

https://github.com/hubblo-org/scaphandre/blob/main/docs_src/explanations/how-scaph-computes-per-process-power-consumption.md

**Comment by vaastav** [comment]
Thanks @mrchrisadams ! This actually helped a lot!
