### ISSUE TITLE
Duplicated HELP and TYPE lines in prometheus exporter

### ISSUE THREAD

**Issue by fabrepe** [hubblo-org/scaphandre#165]
## Bug description

I am trying to scrape prometheus output using InfluxDB's Telegraf client, which is [supported](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/prometheus/README.md) in Telegraf.

It fails with the following errors
```
[inputs.prometheus] Error in plugin: error reading metrics for http://localhost:9090/metrics: reading text format failed: text format parsing error in line 4: second HELP line for metric name "scaph_process_power_consumption_microwatts"
```

In fact metrics sent by prometheus exporter contains several HELP and TYPE definition for the same metric.

```
# HELP scaph_process_power_consumption_microwatts Power consumption due to the process, measured on at the topology level, in microwatts
# TYPE scaph_process_power_consumption_microwatts gauge
scaph_process_power_consumption_microwatts{cmdline="",pid="305600",exe="kworker/2:2-mm_percpu_wq"} 0
# HELP scaph_process_power_consumption_microwatts Power consumption due to the process, measured on at the topology level, in microwatts
# TYPE scaph_process_power_consumption_microwatts gauge
```

## Expected behavior

prometheus TYPE and HELP definition for a given metric should only be defined once  (https://github.com/prometheus/common/issues/265)

## Environment

- Linux distribution version : Debian 11
- Kernel version : 5.10.0-8-amd64

**Comment by bpetit** [comment]
Hi, thanks a lot !

Could you give a try to this branch ? https://github.com/hubblo-org/scaphandre/pull/192

**Comment by dmazhar-cogniance** [comment]
Hey @bpetit , I had the same problem for the latest release. Tried to build the latest `dev` branch and it resolved the problem.

**Comment by bpetit** [comment]
Hi @dmazhar-cogniance !

Thanks a lot for the feedback ! Closing until contrary feedback
