### ISSUE TITLE
newlines in processes name (cmdline) aren't escaped

### ISSUE THREAD

**Issue by billux** [hubblo-org/scaphandre#175]
## Bug description

Newlines in process' cmdline aren't escaped and break Prometheus output format.

## To Reproduce

1. start a process containing a newline in its command line: 
    ```
    # bash -c 'sleep infinity;
    > echo plop'
    ```
2. query metrics endpoint. The response looks like this:
    ```
    […]
    # HELP scaph_process_power_consumption_microwatts Power consumption due to the process, measured on at the topology level, in microwatts
    # TYPE scaph_process_power_consumption_microwatts gauge
    scaph_process_power_consumption_microwatts{cmdline="bash-csleep infinity;
    echo plop",exe="bash",pid="2786006"} 0
    […]
    ```
    Prometheus fails to parse scaphandre's output and ignore all metrics from scaphandre job.

![2022-05-17-182811_1777x101_scrot](https://user-images.githubusercontent.com/222395/168862489-9cdc8226-864f-4166-8a59-6b1e94e9816c.png)

## Expected behavior

newlines should be either escaped or replaced by spaces like in `ps`.

## Environment

- Debian buster
- Kernel version: 5.10.0-9-amd64

Thanks!

**Comment by bpetit** [comment]
@uggla did you open a PR on this ? I see the commit but I cannot find the related PR, did I miss something ?

**Comment by uggla** [comment]
@bpetit yes I wrote a PR to fix this bug.

**Comment by uggla** [comment]
https://github.com/hubblo-org/scaphandre/pull/195

**Comment by bpetit** [comment]
Thanks a lot ! I lost it for a moment.

**Comment by bpetit** [comment]
Applied changes from @uggla in aa15ae288a91184041c4dce19debb869b6a1b385

It is fixed, thanks a lot @billux for raising the issue and @uggla for fixing it !
