### ISSUE TITLE
Energy consumption metrics

### ISSUE THREAD

**Issue by SlimKhiari** [hubblo-org/scaphandre#177]
**Hello Mr Petit,

I'm working on a project to extract and collect energy consumption metrics using your API, and then visualize them graphically.

Indeed, I would like to know please, if it is possible of course, to obtain consumption metrics of the applications running on your servers, or datasets, i.e. "fixed" data, in order to enrich my current dashboard.

Thank you for your help.

Slim KHIARI**

**Comment by bpetit** [comment]
Hi,

Could you precise what your are looking for exactly ?

Have you looked at the [documentation](https://hubblo-org.github.io/scaphandre-documentation/) (and [compatibility section](https://hubblo-org.github.io/scaphandre-documentation/compatibility.html)) to get an overview of what scaphandre does and doesnt today ?
