### ISSUE TITLE
Investigate and at least document why a compilation process may create a difference between total host power and sum of processes power

### ISSUE THREAD

**Issue by bpetit** [hubblo-org/scaphandre#20]
Running a `build --release` of scaphandre with `lto=thin` I see that host total power differs from the sum of all processes power, without catching up.

![screen-weird-diff cleaned](https://user-images.githubusercontent.com/906428/100629678-7b452b00-3321-11eb-99a8-9876af3165b4.png)

It needs to be investigated, then either fixed if fixable or documented if due to the powercap rapl counters behavior. (or even create a bug report about the powercap or intel rapl module ?

Never seen that king of glitch before with any type of process...

**Comment by PierreRust** [comment]
My guest is that the issue does not comes from rapl measurement but from the way this power is splited among processes. I suspect the way cpu % usage for processes is computed can cause the sum of cpu usage to be greater than 100% ( x cpu count), and thus leads a sum of  power greater than exposed by rapl.
I had a quick look at the way this cpu usage is computed and I cannot really say what would be wrong. I guest we should log the computed cpu usage (and maybe the output of `total_time_jiffies`) to see if there is anything fishy going on.

As I said in the chat, I'm also afraid that cpu usage is not an accurate way of splitting energy among process but that's a bit out of topic and could be the subject of an independent discussion.

**Comment by bpetit** [comment]
That's interesting. I don't have a real difference on my laptop. On metrics.hubblo.org, there are some differences, but not especially higher, but also lower. It made me think that there may some differences tetween the metrics given by RAPL from one CPU model to another.

I never had a "constant" different pattern than you have. It would be very interesting to compare different cases.

I think about adding more internal metrics in the prometheus exporter to help with such investigations.

**Comment by bpetit** [comment]
I got the same pattern as you did on other cases (sometimes, the pattern changes over a long period of time too). I'll try to work on that next week. Do you have some resources to share about best practices on splitting the consumption across processes ? I'd like to reflect and discuss on what could be the best way to be more accurate, while staying light and simple.

For the record, I thinks we should investigate how data in /proc are computed as it is what scaph is based on for those computations.

**Comment by bpetit** [comment]
Hi @PierreRust 

I get much better results (comparing total power consumption of all processes to total power consumption of the host) with this fix.

Could you try that too and give me your thoughts ?

Thanks !
