### ISSUE TITLE
RAPL vs IPMI DCMI

### ISSUE THREAD

**Issue by maethor** [hubblo-org/scaphandre#201]
Hi,

I am currently working on RAPL to log power consumption every 10 seconds on around 350 physical servers of various sizes and usage. Full disclosure, I am not using Scaphandre because it was easier to make my own script to fit exactly my needs, but I think we are doing the same thing (reading energy_uj files in `/sys/class/powercap/intel-rapl:*`), and Scaphandre gives me exactly the same result as my script.

Anyway, I saw (in https://github.com/hubblo-org/scaphandre/issues/117#issuecomment-1189360739) that you did some R&D to compare Scaphandre with IPMI card mesurement. I am lucky to work with a public baremetal offer that allows to access IPMI/DCMI data, so I did the same thing.

I now have two weeks of "RAPL sourced" logs for 350 physical servers, and matching "DCMI sourced" logs for 185 of the 350 servers. 

I don't have any experience in statistical analysis, so managing the data carefully is kind of hard for me. For now, it seems that:

- On most servers, RAPL gives me between 3 to 15W, and DCMI typically gives me around 7 to 10W more than RAPL.
- On storage oriented servers with 2 to 6 hard drives, RAPL gives me 10 to 20W but DCMI gives me 60 to 80W
- On highly loaded servers, I can get 50 to 100W in RAPL but 120 to 200W more in DCMI. The worst cases are 87W in RAPL vs 166W in DCMI, and 152W in RAPL vs 277W in DCMI.
- And in the middle of all that, I have curiosities… 15W RAPL vs 15W DCMI… 6W RAPL vs 60W DCMI… 14W RAPL vs 141W DCMI…

I am currently double checking everything, and trying to find some interesting patterns. I am pretty sure I didn't make a huge mistake because I don't have any server where RAPL is greater than DCMI, and the biggest ratio between RAPL and DCMI is 10x. With that said, for now I can't make sense of the differences. And even on the most common cases, where I have 5W in RAPL and 15W in DCMI… it is only 10W but it is 3x difference. At scale, with hundreds of servers, it completely fails to deliver a precise result (except if we are only interested in orders of magnitude).

I wonder if you had the same results in your research, and what you think about all of this. What level of precision should we except from getting power consumption from RAPL, and do you think we could process RAPL power consumption in a more complex function to estimate a more real power usage.

Big fan of your work by the way. And if you want I would be happy to share with you my RAPL and DCMI logs.

Thanks.

**Comment by maethor** [comment]
Hi @bpetit 

Did you have time to think about it? I am still logging data since June, but I am kind of stuck on this project. I would really like to get your feedback and to discuss this issue with you.

I am french btw. I would have loved to offer a beer but I don't leave in Paris. If you have time and if you prefer, we could simply plan for a visio. You can write to me at guillaume at sysnove.fr.

**Comment by bpetit** [comment]
As discussed with @maethor and to lead other readers to the right direction, we now contribute to a collaborative database project on power consumption profiles : https://github.com/boavizta/energizta

It should, at some point. give answers and clarity about differences between multiple sources of power metrics, like RAPL, IPMI, and so on. We'll get metrics from differents sources and start doing some math ;)

Please join and contribute to this project if you are interested !
