### ISSUE TITLE
Riemann exporter

### ISSUE THREAD

**Issue by bpetit** [hubblo-org/scaphandre#21]
It's TCP and protocol buffers, should be okay: http://riemann.io/howto.html#write-a-client

**Comment by uggla** [comment]
May I suggest https://github.com/mcorbin/riemann-rust-client
Mathieu (mcorbin) is available on the "compagnon du devops" forum and may help in Rust and Clojure.

**Comment by bpetit** [comment]
Of course you can. Thanks a lot for those hints. I'll try to create some interest in Mathieu's mind about scaphandre so that he gives us some help regarding that feature then :D

**Comment by uggla** [comment]
@bpetit, I have made a quick test with the rust-riemann_client and it works fine. By the way I have discovered riemann that I never used before.
The client looks pretty simple to use.
So if it ok for you I can take this issue and create the riemann exporter trying to mimic what you did with the prom one.

**Comment by bpetit** [comment]
Hi, of course ! Give it a try !

The prom exporter code may be useful about getting metrics from the sensor, but I guess it won't be regarding the way to ship the metrics, as it should be a push mode here instead of a pull one.

(Just remember that it's the exporter that asks the sensor to collect and store metrics, so you are in control regarding the periodicity and conditions of metrics storage in the buffers and their usage afterwards.)

**Comment by uggla** [comment]
@bpetit, FYI, I made good progress on that topic. Normally, I will be able to send you a PR soon.

**Comment by uggla** [comment]
@bpetit, progressing, I'm just missing the processes values now.
I had a lot of work last week, so I could not finish it. Hopefully that should be ok soon for a first version.
![image](https://user-images.githubusercontent.com/2332209/104138337-bec09980-53a3-11eb-96fd-8c3f237d3230.png)

**Comment by bpetit** [comment]
This is great ! Thanks a lot for the great work 😃 
No worries, that's perfect anyway. I'm very excited about using that feature !

**Comment by uggla** [comment]
Please look at #58

**Comment by bpetit** [comment]
Done and merged. Thanks a lot @uggla !
