### ISSUE TITLE
Json exporter with regex filtering

### ISSUE THREAD

**Issue by hrexha28** [hubblo-org/scaphandre#216]
## Problem

For some use cases, it would be nice to have the energy data stored locally plus be able to specify the process name or pid of which data you want to save in the json file.

## Solution

Implement the regex filter in the JSON exporter

**Comment by bpetit** [comment]
This is done in dev now.

Could you give it a try ?

> 
>       --process-regex <PROCESS_REGEX>
>           Filter processes based on regular expressions (example: 'scaph\\w\\w.e')
>       --container-regex <CONTAINER_REGEX>
>           Filter containers based on regular expressions

**Comment by bpetit** [comment]
Hi,

Last version on the dev branch should fix the issue with process-regex. Regarding container-regex, please ensure you have called the --containers flag as well.

Let me know how it goes. Thanks !

**Comment by bpetit** [comment]
Hi !

Did you get any time/chance to test dev version ?

Thanks !

**Comment by bpetit** [comment]
Closing until someone speaks up :)
