### ISSUE TITLE
Implement --containers option in json exporter

### ISSUE THREAD

**Issue by bpetit** [hubblo-org/scaphandre#217]
## Problem

I'd like to get container labels to metrics I get from json exporter, but the option doesn't exist yet, like it does in prometheus container.

## Solution

Implement the --containers option in json exporter.

**Comment by bpetit** [comment]
Example of usage

`scaphandre --no-header json --containers --max-top-consumers=15 | jq`

**Comment by hrexha28** [comment]
Hi,
I tried to use the --containers option with lxd containers but i get null in the container field for the json exorter.
Is there any way to get the linux container power number?
Thanks

**Comment by bpetit** [comment]
@hrexha28 I've seen your issue, thanks. Will have a look at this for next releases.
