### ISSUE TITLE
Add a configuration file

### ISSUE THREAD

**Issue by cs35-owncloud** [hubblo-org/scaphandre#223]
## Problem

If you have an init script to start scaphandre, or want to automate scaphandre's deployment, it's quite annoying to define scaphandre's parameters in the command line, for example:

```
scaphandre --vm prometheus -a 10.70.10.1 -p 9090
```

## Solution

It would be more convenient to have a configuration file read by default in **/etc/scaphandre/scaphandre.conf**, for example:

```
vm = true
exporter = prometheus
address = 10.70.10.1
port = 9090
```

Thanks.

**Comment by demeringo** [comment]
Related https://github.com/hubblo-org/scaphandre/issues/145

**Comment by bpetit** [comment]
Hi !

I'd say it's a duplicate. Would you mind follow this thread #145 instead ? :)
