### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os

### ISSUE THREAD

**Issue by fmanzano55** [hubblo-org/scaphandre#239]
Hi,

On fresh Ubuntu Server 22.04.1 installed as VM in VMware Fusion : 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/sensors/powercap_rapl.rs:76:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Same error on Ubuntu Desktop and RHL 8 in VMware fusion.

Command line used : scaphandre --vm stdout

It's the build version which was compiled.
Thanks

**Comment by bpetit** [comment]
Hi !

Unfortunately vmware support is not implemented in scaphandre. We would need to develop an exporter like the qemu one but for vsphere, then you should be ablte use the powercap sensor inside the VM
