### ISSUE TITLE
Wrong watt consumptions

### ISSUE THREAD

**Issue by CracKOl** [hubblo-org/scaphandre#241]
## Bug description

First of all, thanks for sharing this tool !

I've deployed the last version on k3S with no pb. Then i have imported the scaphandre dashboard from grafana.com, using its ID : It works fine, i have data displayed but the watt consumption are too low compared to the measure i do with my wattmeter.
I mesure 34w on my device when grafana displays 12 to 15w. 

## Expected behavior

Calculate the right watt consumption.

## Environment

- Linux distribution 22.04
- Kernel version 5.15.0-53-generic
- containerd://1.6.8-k3s1
- k3s v1.24.7+k3s1

Mini server : 
DELL Optiplex 
processor       : 2
vendor_id       : GenuineIntel
cpu family      : 6
model           : 94
model name      : Intel(R) Core(TM) i5-6500T CPU @ 2.50GHz

**Comment by reisub0** [comment]
The power measurement that RAPL measures (which Scaphandre uses) cannot be equal to the wattmeter readings and it will always be lower.

RAPL *estimates* CPU and DRAM power consumption using some features and models that are provided on Intel processors.

CPU and DRAM aren't the only power consuming entities on your system. So when you measure the "Socket power" with the Wattmeter, you are also adding the measurement of the
1. Motherboard
2. NIC
3. Cooling (Fans etc)
4. Peripherals (if any)

<img width="615" alt="image" src="https://user-images.githubusercontent.com/25099244/203559342-3e93628e-894e-4595-a37f-88f331f8d1fd.png"> [1]

The important point about using Scaphandre (or any other software meter) is that it gives you a very accurate way to measure the dynamic aspects of power consumption. You can't really control the power consumption of the PCI slots or motherboard. But you can control the power consumption of the CPU and DRAM by optimizing your workloads.


[1] - A.-C. Orgerie, M. D. de Assuncao, and L. Lefevre, “A survey on techniques for improving the energy efficiency of large-scale distributed systems,” _ACM Comput. Surv._, vol. 46, no. 4, pp. 1–31, Apr. 2014, doi: [10.1145/2532637](https://doi.org/10.1145/2532637).

**Comment by maethor** [comment]
Hello. We are working on this issue in another project which results will eventually be used by Scaphandre and other monitoring tools : https://github.com/hubblo-org/scaphandre/issues/201#issuecomment-1295788596

A difference of ~20W could be mainly explained by storage (~5W per SSD and ~15W per hard drive).

**Comment by bpetit** [comment]
linking this to #140, #117 and #25

**Comment by bpetit** [comment]
link to #116 as well

**Comment by bpetit** [comment]
If your machine supports it, you could now (since 1.0.0) leverage the new PSYS based value that should closer to a wattmeter-based metric (see https://hubblo-org.github.io/scaphandre-documentation/explanations/rapl-domains.html for an explanation on PSYS).

As said previously evaluating other components without RAPL is part of the roadmap, see #24 #330 #289 ...

I'll close this issue as this is somehow a description of the purpose of the whole project to get a wider coverage of components.
