### ISSUE TITLE
How to measure multi-node energy consumption

### ISSUE THREAD

**Issue by FranciscoSedeno** [hubblo-org/scaphandre#242]
Hello! I am using scaphandre with prometheus in a multi node microk8s cluster, but I've seen that scaph_host_power_microwatts only returns (as its name implies) host energy consumption, but I want to get the other nodes' (configured as worker nodes) energy consumption. I've tried with different queries like scaph_process_power_consumption_microwatts but I only get results from the "kubernetes-service-endpoints" job and scaph_domain_power_microwatts isn't what I'm looking for.

If I wanted to measure the other nodes' consumption, how would I do it? Only measuring the consumption for the deployed pods and not the nodes would be fine too.

Thank you very much in advance!

**Comment by mmadoo** [comment]
Hi,
You cound distinct nodes using the `instance` label of the prometheus metrics.
For instance, the query `avg by (instance) (scaph_host_power_microwatts) /1000000` provide consuption per node.

**Comment by FranciscoSedeno** [comment]
@mmadoo Thanks for the advice! I don't know what was happening before but I didn't receive any tuple for the worker node, now I've tried again and everything is fine.

Thanks again!
