### ISSUE TITLE
Not able to install using kubernetes

### ISSUE THREAD

**Issue by deepakagra** [hubblo-org/scaphandre#246]
## Bug description

Not able to install using kubernetes/helm. 

## To Reproduce
1. I am following https://hubblo-org.github.io/scaphandre-documentation/tutorials/kubernetes.html
2.  helm install scaphandre helm/scaphandre is giving following error
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"

## Expected behavior

scaphandre  should get installed

## Environment

minikube version: v1.28.0
 Ubuntu 22.04.1 LTS
$ uname -r 
5.15.0-1026-aws
Client: Docker Engine - Community
 Version:           20.10.22

**Comment by mmadoo** [comment]
PodSecurityPolicy as been removed in k8S 1.25. cf https://kubernetes.io/docs/concepts/security/pod-security-policy/

Our cluster uses k8s 1.23, so I am unable to test a potential fix.

**Comment by rossf7** [comment]
@deepakagra @mmadoo Yes, PSPs were removed in k8s 1.25 https://github.com/hubblo-org/scaphandre/pull/250 has a fix for that.

**Comment by bpetit** [comment]
Hi,

@deepakagra @mmadoo could you try the helm config that is in dev since @rossf7 's PR is merged and give feedback ?

Thanks !

**Comment by mmadoo** [comment]
Sorry, our cluster uses k8s 1.24, so I am unable to test if this issue is fixed

**Comment by bpetit** [comment]
Hi !

Sorry about that @mmadoo.

@deepakagra what about your use case ?

**Comment by bpetit** [comment]
Closing until someone speaks up :)
