### ISSUE TITLE
Scaphandre Windows Installation

### ISSUE THREAD

**Issue by joegharbi** [hubblo-org/scaphandre#247]
Hello everyone,
I would be grateful to all of you if you could help me with the issue I am facing.
I have been trying to compile Scaphandre using Windows 11 for weeks now. I have tried all possible solutions.
Let me tell you my configuration, what I have done so far, and the issue I am facing.

- I have installed windows-rapl-driver and running `driverquery /v | grep -i scaph` result in this: 
<img width="909" alt="Screenshot 2022-12-19 111904" src="https://user-images.githubusercontent.com/57369993/208403338-ba742221-e799-4624-84cd-27695d772240.png">

- I have installed two toolchains versions of rust the MSVC and GNU, I have solved all issues I was facing regarding the Openssl-dev... but ending up with the same issue `libc::pid_t` .. mainly related to `libc` and 2 errors for `os::unix`.
- it really doesn't matter what configuration I use ( GNU using msys2 or MSVC using Microsoft build tools and vcpkg) results always in this   ```Some errors have detailed explanations: E0412, E0425, E0432, E0433, E0599.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `procfs` due to 24 previous errors
warning: build failed, waiting for other jobs to finish... ```.
- I did always make sure to clean my system while switching from GNU to MSVC.
- As far as I understood the `libc` is used with Unix-like environments. Is there a way to overcome this issue?
- My purpose for using the Scaphandre tool is to be able to measure Erlang functions using Windows.

I am open to trying all solutions and propositions.
Thank you all

**Comment by joegharbi** [comment]
Thank you so much.

- Reproducing these steps helped with building scaphandre locally. 
- However, I am not able to use it since the **windows-rapl-driver** seems to not be started yet.
![image](https://user-images.githubusercontent.com/57369993/208949352-e1f2c38f-b142-4807-9877-81c70f327c73.png)
- As I mentioned [earlier ](https://github.com/hubblo-org/scaphandre/issues/247#:~:text=I%20have%20installed%20windows%2Drapl%2Ddriver%20and%20running%20driverquery%20/v%20%7C%20grep%20%2Di%20scaph%20result%20in%20this%3A)it seems that the driver is there but won't be able to start it with `net start ScaphandreDr` 
- I will try to investigate more about the driver issue but it would be great if you can help me if you already have a solution for that.

Thank you so much.

**Comment by joegharbi** [comment]
@tormath1 Thank you so much for the quick reply.
Answering to the three things:  **Yes** I am in **test** mode with **windows 11** and using **Administrator** cmd.

I did some investigations I have these findings if you can confirm which way to proceed:
- I did the build with [MinGW](https://github.com/hubblo-org/windows-rapl-driver#:~:text=Cross%20compilation-,MinGW,-(OUTDATED)). Do you think reinstalling it using [CPUID](https://github.com/hubblo-org/windows-rapl-driver#:~:text=Compilation-,CPUID,-(OUTDATED)) could help? Since when I first tried to install it with MinGW I got a header error `wdmguid.h: No such file or directory`. I solved it adding `-I + path-to-wdmguid.h`.
- When I try to look for the driver I do have this 
<img width="908" alt="image" src="https://user-images.githubusercontent.com/57369993/208979312-a38312f7-8a61-4f5e-90ee-d1990f9c90d4.png"> which is not in the usual system32/drivers folder ( It might be not the actual issue) and by default rebooting after the installation should start the service automatically which was not my case.
- Even after reinstalling it in the system32/drivers folder I still can't start it.
![image](https://user-images.githubusercontent.com/57369993/208983014-d11fef88-dc76-4f01-963c-865cd66f6244.png)

- I have strong doubts about which `ScaphandreDrv.sys` file to have with `DriverLoader.exe` since there are many in the repository, So I might be using the wrong one?
<img width="539" alt="image" src="https://user-images.githubusercontent.com/57369993/208983896-98b9deaa-dc12-46fe-a7e6-699c79f9bc65.png">


Thank you so much for your help

**Comment by joegharbi** [comment]
I was able to run the driver using windows 11.
- In test mode, I used `windows-rapl-driver/kernelland/ScaphandreDrv/x64/Release/ScaphandreDrv/ScaphandreDrv.sys` to build the `DriverLoader.cpp `.

This solved the issue.
I hope this can help future users run scaphandre under windows.

**Comment by demeringo** [comment]
Nice to see it working 👍
Thank you @joegharbi for the feedback and documenting the issue.

**Comment by joegharbi** [comment]
Thank you so much for your help.

**Comment by bpetit** [comment]
Hi @joegharbi 

Happy you could make it. Thanks for sharing this walkthrough, it will help us improve and simplify the procedure.

cc @vico63 this thread shows us what to improve :)

**Comment by Vic063** [comment]
I'll look into that 🙂 
Thank you for your feedback.
