### ISSUE TITLE
Add a --qemu option in prometheus exporter to extract domain/vm name from qemu/kvm process cmdline and make it a label

### ISSUE THREAD

**Issue by bpetit** [hubblo-org/scaphandre#26]
## Problem

When running prometheus exporter on a qemu/kvm host hypervisor, we get metrics for qemu/kvm domains/vms as any other processes. Having the vm/domain name attached to the process metric as a label would make creating appropriate grafana dashboards easier.

## Solution

Adding an option to prom exporter, that enables to extract the vm name (if the process cmdline matches the expected qemu/kvm cmdline pattern) and attach it as a label to the process metrics.

**Comment by uggla** [comment]
@bpetit, looking at that one. If it is ok for you.
If i try to rephrase the above sentence to make sure I understand correctly.
The goal is, if `--vm` is passed to the cmdline, then add a label with the vm hostname to the prom metrics. Is that correct ?

**Comment by bpetit** [comment]
Hi, of course, thanks for that !
It was more about the opposite. When you run the prometheus exporter on a Qemu/kvm hypervisor, the idea would be to tell scaphandre it is an hypervisor with a flag, to ask the prometheus exporter to add a label with the name of the vm on process-level metrics, when this process is in fact a vm. This needs basically some parsing of the exe and cmdline fields that already exist, or maybe double check by querying libvirt to be sure we extract vm names that are actually running.

**Comment by uggla** [comment]
Thanks it looks clearer now, I was completely wrong. :)
So intention is to add a label to qemu processes on the hypervisor to know which vm has the highest cosumption.
Currently I have this output metrics as an exemple:
```
# TYPE process_power_consumption_microwatts gauge
scaph_process_power_consumption_microwatts{exe="qemu-system-x86",cmdline="timestamp=on-...
```

So the idea would be to have:
```
# TYPE process_power_consumption_microwatts gauge
scaph_process_power_consumption_microwatts{exe="qemu-system-x86",vmname="fedora33",cmdline="timestamp=on-...
```
Is that correct ?

**Comment by bpetit** [comment]
Yes, this is the idea ! :)

**Comment by uggla** [comment]
Please look at #41

**Comment by bpetit** [comment]
Merged ! Thanks :)
