### ISSUE TITLE
qemu command does not start the qemu exporter in v0.5.0 (regression)

### ISSUE THREAD

**Issue by TheElectronWill** [hubblo-org/scaphandre#260]
## Bug description

When the `qemu` exporter is enabled via the command line, it is not recognized. That is, `scaphandre qemu` says `scaphandre: Couldn't determine which exporter to run.` and stops. Other exporters like `stdout` work.

## To Reproduce

With Scaphandre 0.5.0, I did:
```
carbo build
./target/debug/scaphandre qemu
```
and got the following error:
```
scaphandre: Couldn't determine which exporter to run.
```

I've also tried with the docker image hubblo/scaphandre:0.5.0 and hubblo/scaphandre:latest, same result.

## Expected behavior

The `qemu` command should enable the qemu exporter, like it did before.

I've tested with previous versions (0.4.1 and 0.4.0), and it works, since I get:
```
> scaphandre qemu
Scaphandre qemu exporter
Sending ⚡ metrics

```

## Environment

- Ubuntu 22.04.1
- `linux 6.1.0-1004-oem`

**Comment by bpetit** [comment]
Thanks for this bug report ! I add it to next batch.

**Comment by TheElectronWill** [comment]
It seems that the problem is that the qemu feature is disabled, because warpten is enabled. Why are the two exclusive?
e.g.
```rust
#[cfg(all(target_os = "linux", not(feature = "warpten")))]
```

**Comment by bpetit** [comment]
iirc it was mainly because the warpten exporter still needs to be rewritten to use MetricGenerator as the other exporters do.

Do you already have a PR somewhere about this or should I open one to fix the exporter, then remove this compilation condition ?

**Comment by TheElectronWill** [comment]
I have a refactoring ready but I cannot make it a PR today... It simplifies how exporters are started and how args are handled, but I have not rewritten the warpten exporter yet.
Thus, if you have a fix for the warpten exporter, go ahead! I'll update my changes and come back :)

**Comment by bpetit** [comment]
should be better in dev now. I'll try to review your refacto PR this week
