### ISSUE TITLE
Add summary to landscape sustainability doc

### ISSUE THREAD

**Issue by catblade** [hubblo-org/scaphandre#264]
Hi,

We are putting together a landscape doc for CNCF Environmental Sustainability TAG. Would be nice to have a summary on this project here.

https://github.com/catblade/wg-env-sustainability/blob/main/documentation/WhitePapers/SustainabilityUseCasesAndLandscape2022.md

Do you have someone who can add a summary? This project is already called out, but not summarized.

I'm one of the chairs for the group. Feel free to contact me on slack or here.

Thanks,
--Marlow

**Comment by bpetit** [comment]
Hi @catblade 

It seems the file is unavailable. Is there another place I should push de description ?

Thanks

**Comment by catblade** [comment]
Ah, we merged it.  File now lives here:
https://github.com/cncf/tag-env-sustainability/blob/main/website/content/about/SustainabilityUseCasesAndLandscape2023.md

Please go ahead and update the description there.
