### ISSUE TITLE
Add --step option to stdout exporter to allow changing time step between measurements

### ISSUE THREAD

**Issue by bpetit** [hubblo-org/scaphandre#27]
## Problem

Right now we can't change the step between two measurements of stdout exporter.

## Solution

This can be easily actionable by adding an option that changes the step variable in the runner function in stdout expoter.

See https://github.com/hubblo-org/scaphandre/blob/main/src/exporters/stdout.rs#L55

**Comment by uggla** [comment]
Please have a look at #31

**Comment by bpetit** [comment]
This is great, thanks. I answered to the PR.

**Comment by bpetit** [comment]
Thank @uggla this is done !
