### ISSUE TITLE
prometheus --containers not adding the extra labels

### ISSUE THREAD

**Issue by BGOtura** [hubblo-org/scaphandre#279]
I am testing scaphandre with the prometheus exporter and the --containers flag, but the metrics exported are not adding any of the extra container-specific labels 

>$ docker run -d -p 9090:9090 prom/prometheus
>$ docker run -v /sys/class/powercap:/sys/class/powercap -v /proc:/proc -d -p 3333:8080 hubblo/scaphandre prometheus --containers

`scaph_process_power_consumption_microwatts{pid="5194",cmdline="/bin/prometheus--config.file=/etc/prometheus/prometheus.yml--storage.tsdb.path=/prometheus--web.console.libraries=/usr/share/prometheus/console_libraries--web.console.templates=/usr/share/prometheus/consoles",exe="prometheus"} 2893`

I would expect the extra labels being shown for the prometheus container ¿?

**Comment by Aude510** [comment]
I had a similar problem. I added the -v option to scaphandre and saw that scaphandre was unable to find /var/run/docker.sock 
I added this as a container volume and it now works, but I am unsure about while it's good practice to solve the issue this way.

**Comment by bpetit** [comment]
Hi @BGOtura !

Does @Aude510 problem look the same as yours ?
Or do you get it even with the docker socket accessible to scaphandre ?

**Comment by bpetit** [comment]
Closing until someone speaks up :)
