### ISSUE TITLE
Some links in the documentation seem to be broken

### ISSUE THREAD

**Issue by mtakeshi1** [hubblo-org/scaphandre#288]
## Bug description

Hi. 

First of all, if it's not the right way to report issues like this, I apologize in advance. In the getting_started.md file, the links for the installation and compilation are wrong (or the sections that they refer to):
```
[Installation on GNU/Linux](installation_linux.md) section.
```
should be 
```
[Installation on GNU/Linux](installation-linux.md) section.
```
as the same goes for the other links.

I did clone the documentation and re-generated it with the right links, but since the misspelling originated in the main project, I was not sure how to proceed. In any case, I'm more than happy to create the PR to fix these, I just need some pointers as to where should I create the PR.

## To Reproduce

1. Navigate to: [Getting Started](https://hubblo-org.github.io/scaphandre-documentation/tutorials/getting_started.html)
2. Click on any of the 4 top links

## Expected behavior

You should be redirected to the corresponding section.

## Environment

- Any browser

**Comment by bpetit** [comment]
Should I close this one as #259 is merged ? Or should it be the starting point to automate checks on the doc ?
