### ISSUE TITLE
Clarification: what's the unit of the `consumption` from the JSON exporter?

### ISSUE THREAD

**Issue by HongyuHe** [hubblo-org/scaphandre#290]
Greetings!

I wonder what the unit is of the `consumption` per process from the JSON exporter.
Is it energy or power? 
Is it microwatt, microwatt second/hour or microjoule?

Thanks in advance for helping me.

**Comment by demeringo** [comment]
Hi @HongyuHe 

Thank you for reaching out.

My understanding is that this returns the _instantaneous / immediate_  power consumption in microwatts (i.e the power, not the energy).

See https://github.com/hubblo-org/scaphandre/discussions/251 

Do not hesitate to add a comment on the above discussion if you feel we should document it better (or even better, if you can, feel free to open a PR on the documentation to help improve it ;-))

**Comment by HongyuHe** [comment]
That's very clear! Thanks very much for your help, @demeringo!
