### ISSUE TITLE
Electricity consumption not shown on Ubuntu KVM

### ISSUE THREAD

**Issue by ivan-koryshkin** [hubblo-org/scaphandre#312]
## Bug description

I'm trying to set up an electricity consumption collection using "scaphandre" from the Green Software Foundation repository.
I noticed that the documentation states that the program works both with virtual machines and with bare-metal ones. I was successfully able to set it up on real machines.
But it doesn't work with virtual machines.
I have a virtual machine with kvm virtualization, but "scaphandre" shows power consumption equal to 0 (screenshot 2). Although the same powertop works well (screenshot 1).

## To Reproduce
run on virtual machine (VDS-KVM)
sudo docker run -v /sys/class/powercap:/sys/class/powercap -v /proc:/proc -ti hubblo/scaphandre stdout -t 15

## Expected behavior

Electricity consumption shown

## Screenshots
![Screenshot from 2023-05-15 17-03-23](https://github.com/hubblo-org/scaphandre/assets/37804571/0678a5b5-45db-4f57-990c-4b4b90a48506)
![Screenshot from 2023-05-15 17-03-03](https://github.com/hubblo-org/scaphandre/assets/37804571/16b221e9-97b4-4abd-8f37-cdd9c9b09bb3)

## Environment

Type: VDS-KVM 
System:  Ubuntu 5.4.0-29-generic

**Comment by ivan-koryshkin** [comment]
As far as I understand this method for domain owners, I have only a few virtual machines, I have no access to the domain. Please correct me if I'm wrong

**Comment by bpetit** [comment]
You're right, it's made for bare metal machine owners / private cloud staff / ...

Scaphandre doesn't provide ([yet](https://github.com/hubblo-org/scaphandre/issues/25)) a mean to evaluate the power usage on a virtual machine without gathering metrics from the bare metal host first.
