### ISSUE TITLE
Some metrics are set to 0 after docker scaphandre:dev restart

### ISSUE THREAD

**Issue by mmadoo** [hubblo-org/scaphandre#343]
## Bug description

I have kubernetes worker with a scaphandre pod (running image hubblo/scaphandre:dev).
I have restarted it in order to update image and now I have 0 for lot of metrics:
```
# HELP scaph_host_power_microwatts Power measurement on the whole host, in microwatts
# TYPE scaph_host_power_microwatts gauge
scaph_host_power_microwatts 0
# HELP scaph_host_energy_microjoules Energy measurement for the whole host, as extracted from the sensor, in microjoules.
# TYPE scaph_host_energy_microjoules counter
scaph_host_energy_microjoules 0
scaph_process_power_consumption_microwatts{container_scheduler="docker",container_id="e4bf06cbb1ff",pid="87635",cmdline="nginx: worker process",exe=""} 0
...
```
The previous container running an image with same name but created 73 days ago (2023-06-09) does not have such issue.

## To Reproduce
Start a scaphandre with latest dev image

## Environment

- Linux distribution version: Ubuntu jammy
- Kernel version : 5.15.0-71-generic
- K8s:  1.24.10
- Functionnal docker image: 
```
docker image ls  hubblo/scaphandre:dev
REPOSITORY          TAG       IMAGE ID       CREATED        SIZE
hubblo/scaphandre   dev       ad2baba8e081   2 months ago   103MB
```
- **non** functional docker image:
```
docker image ls  hubblo/scaphandre:dev
REPOSITORY          TAG       IMAGE ID       CREATED      SIZE
hubblo/scaphandre   dev       727016a2ea09   6 days ago   103MB
```

**Comment by mmadoo** [comment]
The metrics scaph_socket_energy_microjoules is not 0
In following grafana capture, we could see that for worker-dcbrain-dev-01 (which use a latest dev version)  that scaph_host_power_microwatts returns 0 while scaph_socket_energy_microjoules gives expected result.

![image](https://github.com/hubblo-org/scaphandre/assets/1867448/9e842264-373f-4e0a-afdd-4f8110703af4)

**Comment by bpetit** [comment]
Hi,

I think this issue has just been fixed in dev. Could you try with the latest dev image ?

Thanks

**Comment by mmadoo** [comment]
I confirm that issue is fixed with latest dev image

**Comment by blupblup46** [comment]
Hi, I work in the same organization as @mmadoo and the metrics from `sum(scaph_process_power_consumption_microwatts) by (node)` and `sum( scaph_socket_power_microwatts) by (node)` show different results.
Previously, these metrics reported 0 watt consumption for every processes
![image](https://github.com/hubblo-org/scaphandre/assets/90987010/4571b772-49ee-45af-ae4b-eba1f56f1122)

Do you know where it could come from ?
Do you think it could come from a problem on accounting for multiple core CPUs ?
Thanks !

**Comment by bpetit** [comment]
Hi ! Could you open a new issue for this behavior with some graphs or data ? Thanks !
