### ISSUE TITLE
Wrong Wattage gets displayed for a Programm

### ISSUE THREAD

**Issue by Haron123** [hubblo-org/scaphandre#348]
## Bug description

When i try to measure the power consumption of a programm, it displays a way too high power consumption for the
highest consuming programm, though it doesnt always do that, only when the highest programm uses a lot of the CPU, though not enough to explain the high consumption.

## To Reproduce

In the Terminal enter : `sudo scaphandre stdout -t 300`

check the Package Power consumption.

Start a stresstest on a single cpu core

The way i did it is : 
In another Terminal i enter `stress -c 1`

Check Package consumption, and the power consumption of the stress programm.

You should notice a big discrepancy

## Expected behavior
Correct display of the programms Wattage

## Screenshots

Here you can see it tells me that the stress on a single cpu core consumes 24 Watts,
while the whole package draws ~28W
https://i.imgur.com/5DBZsOt.png

But here without Stress it only lowered the Package power consumption by ~5W down to ~22W
which doesnt seem correct. This also isnt a rarity when i retry it.

https://imgur.com/VxijYTu.png

On a small note, my socket power only goes up by about 5-10W when starting stress so i doubt its actually 24W

## Environment

- Linux distribution version : Manjaro Linux 23.0.0 Uranos
- Kernel version : 5.16.18-1-MANJARO

## Additional context

I Seem to have the same issue with a similar tool called PowerJoular, is this simply the weakness of such programms or an error on my side ?

**Comment by bpetit** [comment]
Hi,

Next version uses a better allocation logic for per-program consumption, could you give a try to latest dev code to see if it seems more accurate in your context ?

Another feedback on this would be great.

Thanks

**Comment by Haron123** [comment]
Hey bpetit, I tried the dev branch, and it seems to measure the programs correctly now.

https://i.imgur.com/ByBF8Os.png
https://i.imgur.com/VWbFGXT.png

The stress tool used on 1 and 2 cores gives me the correct results that i would expect (I had 5w as a result of many tests before with a lot of other methods and the same stress tool, so I'm certain it's correct).

Good job, I'm happy it's fixed !

Have a great day.
