### ISSUE TITLE
.json file output format

### ISSUE THREAD

**Issue by ErwinBoltz** [hubblo-org/scaphandre#369]
Hello !

To begin, just wanted to say thanks :1st_place_medal: 

i'm not quite sure this is an unexpected behavior so please tell me if i'm missing something or doing something wrong !

## Bug description

The .json file when using json exporter is incorrectly outputed.

## To Reproduce

My goal was to use scaphandre in order to monitor the consumption of a docker container.
So for example i did this :

`./scaphandre json --containers -t 15 -s 5 -f report.json`

you will get a report.json file formated like this :

{"host": { ... } }{"host": { ... } }{"host": { ... } }

The problem is that if you want to use this json file ( i'm using Python in order to get the data i'm interessed in )  it contains multiple JSON objects concatenated together without proper separation.

This format causes the JSON parser to encounter an error because it expects only one JSON object per file.

## Expected behavior

 Each JSON object should be separated by a comma , or be placed in an array [...].

[
    {"host": { ... } },
    {"host": { ... } },
    {"host": { ... } }
]

or 

{"host": { ... } },
{"host": { ... } },
{"host": { ... } }

## Environment

- Linux distribution version [Pop!_OS 22.04 LTS]
- Kernel version [6.6.10-76060610-generic]

**Comment by ErwinBoltz** [comment]
if anyone needs it i did a bash script in order to reformat in a valid json format :

```
#!/bin/bash

input_file="report.json"
output_file="formatted_report.json"

# Check if input file exists
if [ ! -f "$input_file" ]; then
    echo "Input file $input_file not found."
    exit 1
fi

# Check if jq is installed
if ! command -v jq &> /dev/null; then
    echo "jq is required but it's not installed. Aborting."
    exit 1
fi

# Process input file and format output
jq -s '.' "$input_file" > "$output_file"

echo "Output written to $output_file"
```

**Comment by joegharbi** [comment]
Hello,
Thank you for documenting this bug.
And congratulations to the team for the great progress.

I've been using scaphandre json exporter for more than a year since V0.5.0 and had no issues.

I'm also facing the same issue as soon as I installed the new version v1.0.

My environment is windows 11 which means it's a platform independent issue appeared with the latest release. 

Looking forward to hearing from you soon.

**Comment by bpetit** [comment]
Hi !

Thank you for raising this issue, I tried a PR [here](https://github.com/hubblo-org/scaphandre/pull/382).

Let me know if you can try this branch before it makes it to dev, I'd love to hear feedbacks.

**Comment by joegharbi** [comment]
Hi, 
Thank you for your time and effort.
Unfortunately, I still have the same issue with the JSON exporter.
I am using Windows 11.

**Comment by bpetit** [comment]
Hi,

Did you build scaphandre on the branch '369-json-file-output-format' ?

**Comment by ErwinBoltz** [comment]
Hello, just tried it, works fine for me. Thanks for your work ! :+1:

**Comment by joegharbi** [comment]
Hi @bpetit Yes that's what I did.

**Comment by bpetit** [comment]
Hi !

Thanks @ErwinBoltz for the feedback.

@joegharbi this has been merged to dev. Could you confirm, you still have the issue with the latest dev and provide an output please ?

**Comment by joegharbi** [comment]
@bpetit Good news it is now giving the correct format from the json exporter.
However, there are some errors as shown in the attached screenshot.
![Screenshot 2024-05-06 140437](https://github.com/hubblo-org/scaphandre/assets/57369993/91545b23-9708-4c7c-a613-a6e3966c6d15)
Thank you.

**Comment by bpetit** [comment]
This is another issue. It might be because the driver is not properly set up. Did you install it as an administrator (this is still needed, but might not be needed in the future) ?

Could you open a dedicated issue if it remains as it is ? thanks

**Comment by joegharbi** [comment]
@bpetit Yes I installed it as an administrator. 
I opened this new issue https://github.com/hubblo-org/scaphandre/issues/384 but I think it is linked to this one too https://github.com/hubblo-org/scaphandre/issues/376.
Thank you.

**Comment by bpetit** [comment]
Lets follow up on #376 @joegharbi then :)
