### ISSUE TITLE
Error:  Couldn't find intel_rapl modules.

### ISSUE THREAD

**Issue by yunnniverse** [hubblo-org/scaphandre#383]
## Bug description
I tried to run scaphandre on wsl2(Ubuntu 22.04)

yunni@yunni:/$ scaphandre stdout -t 5
scaphandre::sensors::powercap_rapl: Couldn't find intel_rapl modules.
thread 'main' panicked at src/sensors/powercap_rapl.rs:158:53:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

## To Reproduce
$ scaphandre stdout -t 5
scaphandre::sensors::powercap_rapl: Couldn't find intel_rapl modules.
thread 'main' panicked at src/sensors/powercap_rapl.rs:158:53:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }

## Expected behavior
When I tried this process on linux machine, succeed. (Which mean I could see scaphandre output)

## Screenshots
![image](https://github.com/hubblo-org/scaphandre/assets/102639386/41c475dc-0fd3-458d-a40a-f018108e4b41)

## Environment
- Linux distribution version : Ubuntu 22.04.3 LTS
- Kernel version : 5.15.146.1-microsoft-standard-WSL2

## Additional context
I searched some information about this problem, and I found that there is no powercap folder at all and my /usr/src is empty too.

**Comment by vbmade2000** [comment]
@yunnniverse From https://askubuntu.com/questions/1148528/how-to-enable-kernel-configs-config-powercap-and-config-intel-rapl-in-ubuntu, can you execute following grep commands and check? They show if the module is available.

```
doug@s15:~/temp-k-git/linux$ grep CONFIG_POWERCAP /boot/config-4.4.0-141-generic
CONFIG_POWERCAP=y
doug@s15:~/temp-k-git/linux$ grep CONFIG_INTEL_RAPL /boot/config-4.4.0-141-generic
CONFIG_INTEL_RAPL=m
```

**Comment by bpetit** [comment]
Hi @yunnniverse !

How does it go with the commands @vbmade2000 suggested ?

**Comment by yunnniverse** [comment]
> @yunnniverse From https://askubuntu.com/questions/1148528/how-to-enable-kernel-configs-config-powercap-and-config-intel-rapl-in-ubuntu, can you execute following grep commands and check? They show if the module is available.
> 
> ```
> doug@s15:~/temp-k-git/linux$ grep CONFIG_POWERCAP /boot/config-4.4.0-141-generic
> CONFIG_POWERCAP=y
> doug@s15:~/temp-k-git/linux$ grep CONFIG_INTEL_RAPL /boot/config-4.4.0-141-generic
> CONFIG_INTEL_RAPL=m
> ```

@bpetit  Oh my god I'm so sorry—I completely missed @vbmade2000's commands.. I’ve since changed my environment from WSL to Linux, so I’m no longer able to try it out.. Im so sorry

**Comment by bpetit** [comment]
And sorry on my side as I missed that it was actually WSL.

It's expected that it doesn't work on WSL as it surely doesn't include powercap module :)

Running Scaphandre on windows requires the [windows-rapl-driver](https://github.com/hubblo-org/windows-rapl-driver/) (included in the exe installer available on the recent releases).

Thanks for your answer and for clarifying the issue !
