### ISSUE TITLE
Add cargo test --all in CI

### ISSUE THREAD

**Issue by uggla** [hubblo-org/scaphandre#43]
Add `cargo test --all` in the CI to check all tests are working and avoid regressions.

**Comment by bpetit** [comment]
Hi,

We can't simply do that. Github actions are running on virtual machines, so the tests based on the powercap rapl sensor will fail. I've setup a CD (awx) endpoint with a bare metal worker, I'll try to link the CI to it soon.

**Comment by uggla** [comment]
@bpetit, if it can help, I have a bare metal server, I can create a ssh account for you.

**Comment by bpetit** [comment]
Thanks. I have a machine setup. I just need to link github events to awx webhooks. I hope I'll make it work in a few days.

**Comment by bpetit** [comment]
This is done, running cargo build, stdout -t 2 and cargo tests --all on all PRs.

This surely can be improved. It's running on an AWX instance. The playbook related to the actions job is [there](https://github.com/hubblo-org/ansible-scaphandre/blob/master/validate_gh.yml).
