### ISSUE TITLE
Broken tutorial link on website homepage

### ISSUE THREAD

**Issue by Pixep** [hubblo-org/scaphandre#47]
## Bug description

On the page https://hubblo-org.github.io/scaphandre/index.html, the `tutorials` link points to a 404
https://hubblo-org.github.io/scaphandre/tutorials/overview.html

## To Reproduce

Navigate to the website, and click the link of course :)

## Screenhost

![image](https://user-images.githubusercontent.com/18591372/103815493-490da400-5018-11eb-9245-22e198fc627d.png)

**Comment by bpetit** [comment]
Hi,

Thans for the warning. It seems to me this may due to some old cache as this page has been moved. If I go the doc I don't see it as a link.

Please note that the doc is still being built and not yet merged in master. So some changes should still be mde before it happens.

**Comment by bpetit** [comment]
@Pixep do you see the documentation correctly now ?

**Comment by Pixep** [comment]
Hey, still the same issue. But I believe it is more a broken link issue on the home page, because the links from the home page work fine. This one, however (`here` link on the homepage), redirects to something that doesn't exist (anymore?)

> (The code **documenentation** itself is **here**)

**Comment by bpetit** [comment]
It should be better now. Could you confirm ? :)

**Comment by Pixep** [comment]
Yes, much better, thanks!

**Comment by bpetit** [comment]
Thank you !
