### ISSUE TITLE
Allow to easily and locally test scaphandre with dashboards

### ISSUE THREAD

**Issue by bpetit** [hubblo-org/scaphandre#53]
## Problem

It would be great to be able a full scaphandre-based scenario locally, in one command.

## Solution

We already have a docker image for scaphandre. I imagine we could provide such an option with a proper dockerfile that runs scaphandre, grafana and prometheus locally. It would also require to automatically do some configuration on prometheus and grafana:
- feed prometheus.yml used by the prom container with the right target (http://localhost:8080/metrics)
- create a default dashboard on grafana to show state-of-the-art metrics from the current host
- create automatically a datasource for prometheus in grafana

## Alternatives

Any alternative to a docker-compose file that would run easily locally without much "unusual" dependencies (to a "techie") would be okay.

## Additional context

Here are some ressources to help on the additional automation steps:
- https://www.metricfire.com/blog/grafana-tutorial-automating-common-grafana-actions/

**Comment by bpetit** [comment]
I've moved docker-compose stuff in the docker-compose folder (instead of sample-stack).

Don't hesitate to open new PRs to add or improve dashboards, or add easy-to-install components (based on other docker images than prometheus for example) that you would like to deploy easily on local developments platforms.

**Comment by desrod** [comment]
I see references to several Grafana dashboards but nobody has yet shared their dashboards anywhere. Is there a repository where these various dashboards are being hidden, so those of us interested in using and promoting Scaphandre and start from? Surely you don't want everyone to start from scratch, right?

**Comment by bpetit** [comment]
The dashboard showed in this thread is in the docker-compose folder, and you  should have it up and running locally if you run the docker compose stack.

The [demo dashboard](https://metrics.hubblo.org) is not shared, but I could put the json in the repository if this is of any help.

Having a dedicated repo for community dashboards is a great idea, thanks ! I might create one soon.

**Comment by khalvai** [comment]
is there any improvment?
i was looking for a dashbord that would visualize the consumption of an application.
if there would be a custom dashboard for this purpose, please keep me posted. 
thanks

**Comment by bpetit** [comment]
I think there is. Did you try the docker compose ? It provides a basic but usable dashboard.
