### ISSUE TITLE
Remove docs/ output from the source code

### ISSUE THREAD

**Issue by bpetit** [hubblo-org/scaphandre#63]
## Problem

I've added the generated static html documentation from mdbooks in the source code to release fast. This is highly inconvenient as it pollutes the pull requests reviews with conflicts. Those are easy to deal with, by cleaning docs and running mdbooks build, but are still disturbing.

## Solution

Create workflow to build the documentation in a separate repository, handled by github pages.

## Alternatives

Any trick that would make the pages being built and presented the same way it is now, without storing the html result in the source code repo would be ok.

## Additional context

Github pages is convenient, it would be better to keep using it.

**Comment by uggla** [comment]
I think it is better to keep the doc, part of the repo.
By the way we can move the pictures at the root of the project into a images folder. Root will be cleaner.

**Comment by bpetit** [comment]
Do you mean keeping the html generated doc ? Don't you think it's a mess to have it there ?
I was not thinking about moving the docs_src folder, but just build the docs one with github actions, to not include the resulting files in the git history.
