### ISSUE TITLE
JsonExporter to investigate remote bug patterns, or enable specific post processing

### ISSUE THREAD

**Issue by bpetit** [hubblo-org/scaphandre#66]
## Problem

When we encounter a unusual buggy pattern on a specific host we don't have access to, we don't have yet a way to ask for data that could lead us to the solution.

## Solution

Create a JsonExporter to extract the data got from the sensor in json files, to allow further investigations or post-processing (could be useful to develop scripts based on scaphandre data).

## Alternatives

Maybe CSV could be useful for human reading/or not fully-automated investigations ?

**Comment by bpetit** [comment]
@wallet77 I think you had a use case about that. Let's merge efforts as soon as you have time for that :)

**Comment by wallet77** [comment]
@bpetit I can start to work on it this week.

**Comment by bpetit** [comment]
First version is working and merged. Thanks a lot @wallet77 !
Let's open new issues for more specific needs on that exporter and further enhancements !
