### ISSUE TITLE
[DOC] Add compiler instruction in installation process

### ISSUE THREAD

**Issue by wallet77** [hubblo-org/scaphandre#67]
## Problem

When I followed the steps to install/compile the project I got this error:
```bash
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: aborting due to previous error

error: could not compile `log`
```

## Solution

Just install a gcc compiler:
`sudo apt install build-essential`

We should add this information in the doc.
I will take care of it soon ;)

**Comment by bpetit** [comment]
Is this ok like that ? [https://hubblo-org.github.io/scaphandre-documentation/troubleshooting.html#trying-to-build-the-project-i-get-this-error](https://hubblo-org.github.io/scaphandre-documentation/troubleshooting.html#trying-to-build-the-project-i-get-this-error)

:)

**Comment by wallet77** [comment]
LGTM ;)

**Comment by bpetit** [comment]
🥳
