### ISSUE TITLE
thread 'main' panicked at 'Couldn't find intel_rapl modules.' on debian

### ISSUE THREAD

**Issue by maximeperrault** [hubblo-org/scaphandre#73]
### Bug description

Unable to start scaphandre

## To Reproduce

`docker run -v /sys/class/powercap:/sys/class/powercap -v /proc:/proc -e RUST_BACKTRACE=full -ti hubblo/scaphandre stdout -t 15`

## Expected behavior

The container starts and write data on stdout
Screenshots
```
thread 'main' panicked at 'Couldn't find intel_rapl modules.', src/sensors/powercap_rapl.rs:72:13
stack backtrace:
   0:     0x5597fe40581a - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x5597fe40581a - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x5597fe40581a - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:     0x5597fe40581a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:     0x5597fe247eac - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:     0x5597fe404ed1 - std::io::Write::write_fmt::haeeb374d93a67eac
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:     0x5597fe4047cb - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:     0x5597fe4047cb - std::sys_common::backtrace::print::h301abac8bb2e3e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:     0x5597fe4047cb - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:     0x5597fe4047cb - std::panicking::default_hook::h9b1a691049a0ec8f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:     0x5597fe4047cb - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:     0x5597fe3f5ec3 - std::panicking::begin_panic::{{closure}}::h5d96da62289ff715
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:506
  12:     0x5597fe3f5e9c - std::sys_common::backtrace::__rust_end_short_backtrace::hb256569b5c3cbfe0
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:     0x5597fe3b308a - std::panicking::begin_panic::hadf109fd9be01ce1
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:505
  14:     0x5597fe3eb68a - <scaphandre::sensors::powercap_rapl::PowercapRAPLSensor as scaphandre::sensors::Sensor>::generate_topology::h869517b2dbd7c71d
                               at /app/src/sensors/powercap_rapl.rs:72
  15:     0x5597fe3ebf47 - <scaphandre::sensors::powercap_rapl::PowercapRAPLSensor as scaphandre::sensors::Sensor>::get_topology::h1040dc885fedd540
                               at /app/src/sensors/powercap_rapl.rs:112
  16:     0x5597fe355ef4 - scaphandre::exporters::stdout::StdoutExporter::new::h8a54684990fe59de
                               at /app/src/exporters/stdout.rs:51
  17:     0x5597fe355ef4 - scaphandre::run::hf55fdcee5038083e
                               at /app/src/lib.rs:60
  18:     0x5597fe184e43 - scaphandre::main::h6f1f01f23d78ccc7
                               at /app/src/main.rs:92
  19:     0x5597fe4016d3 - core::ops::function::FnOnce::call_once::h2d5aac1dbac46353
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:227
  20:     0x5597fe4016d3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8f018f9477126d9a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:137
  21:     0x5597fe1852e5 - main
  22:     0x7fc662e98cb2 - __libc_start_main
  23:     0x5597fe18109a - _start
  24:                0x0 - <unknown>
```

 ## Environment

* Linux distribution version

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.12 (stretch)
Release:	9.12
Codename:	stretch
```

* Kernel version

```
$ uname -r
4.9.0-12-amd64
```
I have already tried the solution you gave to #59 but I still have an issue when I try to install linux-modules-extra packages and I have the following issue : 

```
sudo apt install linux-modules-extra-$(uname -r)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package linux-modules-extra-4.9.0-12-amd64
E: Couldn't find any package by glob 'linux-modules-extra-4.9.0-12-amd64'
E: Couldn't find any package by regex 'linux-modules-extra-4.9.0-12-amd64'
```

**Comment by bpetit** [comment]
Hi,

Thanks for reporting ! Do you have files in /sys/class/powercap/ ?

**Comment by maximeperrault** [comment]
Re, 

I don't have files in ` /sys/class/powercap/`
I just dockerized the latest version from github and i got the same error.

```
lsmod | grep rapl
intel_rapl_perf        16384  0
```
Thank you.

**Comment by bpetit** [comment]
Did you get the exact same stacktrace with the latest version ? 🤔

**Comment by maximeperrault** [comment]
You're right. There it is : 

scaphandre::sensors::powercap_rapl: Couldn't find intel_rapl modules.
thread 'main' panicked at 'Trick: if you are running on a vm, do not forget to use --vm parameter invoking scaphandre at the command line', src/sensors/mod.rs:238:18
stack backtrace:
   0:     0x55d3339b711a - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x55d3339b711a - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x55d3339b711a - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:     0x55d3339b711a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:     0x55d3337fa19c - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:     0x55d3339b67d1 - std::io::Write::write_fmt::haeeb374d93a67eac
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:     0x55d3339b60cb - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:     0x55d3339b60cb - std::sys_common::backtrace::print::h301abac8bb2e3e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:     0x55d3339b60cb - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:     0x55d3339b60cb - std::panicking::default_hook::h9b1a691049a0ec8f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:     0x55d3339b60cb - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:     0x55d3339d23b8 - std::panicking::begin_panic_handler::{{closure}}::h101ca09d9df5db47
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:     0x55d3339d2384 - std::sys_common::backtrace::__rust_end_short_backtrace::h3bb85654c20113ca
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:     0x55d3339d233d - rust_begin_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:     0x55d3337f78a0 - core::panicking::panic_fmt::h48c31e1e3d550146
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
  15:     0x55d3337fe6b2 - core::option::expect_failed::hf3f43f1792267e24
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1226
  16:     0x55d3339505ed - core::option::Option<T>::expect::h1d2151c9c2d652aa
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:346
  17:     0x55d3339505ed - scaphandre::sensors::Topology::add_cpu_cores::h7d23931f9ff69840
                               at /app/src/sensors/mod.rs:234
  18:     0x55d33398f151 - <scaphandre::sensors::powercap_rapl::PowercapRAPLSensor as scaphandre::sensors::Sensor>::generate_topology::h8b771600fb2688b8
                               at /app/src/sensors/powercap_rapl.rs:106
  19:     0x55d333990347 - <scaphandre::sensors::powercap_rapl::PowercapRAPLSensor as scaphandre::sensors::Sensor>::get_topology::hb65fc2a32bd7f703
                               at /app/src/sensors/powercap_rapl.rs:112
  20:     0x55d333907924 - scaphandre::exporters::stdout::StdoutExporter::new::h2c386abeb6cb01be
                               at /app/src/exporters/stdout.rs:51
  21:     0x55d333907924 - scaphandre::run::h4bfb5995a2909473
                               at /app/src/lib.rs:60
  22:     0x55d333736e43 - scaphandre::main::hf6b720fe640825d8
                               at /app/src/main.rs:92
  23:     0x55d3339b2ff3 - core::ops::function::FnOnce::call_once::hb8b31c0b0b2918aa
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:227
  24:     0x55d3339b2ff3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h69b16c01bbf36f97
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:137
  25:     0x55d3337372e5 - main
  26:     0x7f5e84c64cb2 - __libc_start_main
  27:     0x55d33373309a - _start
  28:                0x0 - <unknown>

**Comment by maximeperrault** [comment]
And with the --vm parameter : 

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/sensors/powercap_rapl.rs:76:53
stack backtrace:
   0:     0x55f53f27611a - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x55f53f27611a - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x55f53f27611a - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:     0x55f53f27611a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:     0x55f53f0b919c - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:     0x55f53f2757d1 - std::io::Write::write_fmt::haeeb374d93a67eac
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:     0x55f53f2750cb - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:     0x55f53f2750cb - std::sys_common::backtrace::print::h301abac8bb2e3e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:     0x55f53f2750cb - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:     0x55f53f2750cb - std::panicking::default_hook::h9b1a691049a0ec8f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:     0x55f53f2750cb - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:     0x55f53f2913b8 - std::panicking::begin_panic_handler::{{closure}}::h101ca09d9df5db47
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:     0x55f53f291384 - std::sys_common::backtrace::__rust_end_short_backtrace::h3bb85654c20113ca
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:     0x55f53f29133d - rust_begin_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:     0x55f53f0b68a0 - core::panicking::panic_fmt::h48c31e1e3d550146
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
  15:     0x55f53f0bd742 - core::option::expect_none_failed::h6154dc750ae47ade
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
  16:     0x55f53f24eda6 - core::result::Result<T,E>::unwrap::h6c4fc165a30e1d5c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/result.rs:973
  17:     0x55f53f24eda6 - <scaphandre::sensors::powercap_rapl::PowercapRAPLSensor as scaphandre::sensors::Sensor>::generate_topology::h8b771600fb2688b8
                               at /app/src/sensors/powercap_rapl.rs:76
  18:     0x55f53f24f347 - <scaphandre::sensors::powercap_rapl::PowercapRAPLSensor as scaphandre::sensors::Sensor>::get_topology::hb65fc2a32bd7f703
                               at /app/src/sensors/powercap_rapl.rs:112
  19:     0x55f53f1c6924 - scaphandre::exporters::stdout::StdoutExporter::new::h2c386abeb6cb01be
                               at /app/src/exporters/stdout.rs:51
  20:     0x55f53f1c6924 - scaphandre::run::h4bfb5995a2909473
                               at /app/src/lib.rs:60
  21:     0x55f53eff5e43 - scaphandre::main::hf6b720fe640825d8
                               at /app/src/main.rs:92
  22:     0x55f53f271ff3 - core::ops::function::FnOnce::call_once::hb8b31c0b0b2918aa
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:227
  23:     0x55f53f271ff3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h69b16c01bbf36f97
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:137
  24:     0x55f53eff62e5 - main
  25:     0x7fe3b7589cb2 - __libc_start_main
  26:     0x55f53eff209a - _start
  27:                0x0 - <unknown>

```

**Comment by bpetit** [comment]
Thanks. I forgot to ask: did you run a `modprobe intel_rapl` first ?

**Comment by maximeperrault** [comment]
Yeah I got a error : 
`modprobe: ERROR: could not insert 'intel_rapl': No such device`

**Comment by bpetit** [comment]
Okay, unfortunately it's more likely because your CPU doesn't embbed RAPL capabilities. I should have asked about that first. What do you have in /proc/cpuinfo ?

**Comment by maximeperrault** [comment]
Here we go : 
```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
stepping	: 4
microcode	: 0x2006906
cpu MHz		: 2499.998
cache size	: 33792 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single kaiser fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
bogomips	: 4999.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
stepping	: 4
microcode	: 0x2006906
cpu MHz		: 2499.998
cache size	: 33792 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single kaiser fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
bogomips	: 4999.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

```

**Comment by bpetit** [comment]
I didn't find it on ark.intel.com, but if I look at ark pages for models from the same family (found [here](https://en.wikipedia.org/wiki/List_of_Intel_Skylake-based_Xeon_microprocessors#Xeon_Platinum_(octa_processor))) like [this one](https://ark.intel.com/content/www/us/en/ark/products/136874/intel-xeon-platinum-8174-processor-33m-cache-3-10-ghz.html) I don't find the "Thermal Monitoring Technologies" item that usually says if RAPL is available.

So I guess you don't have the hardware required for the measurement :/

There is a discussion [here](https://github.com/hubblo-org/scaphandre/issues/25) to integrate an estimation-based feature in scaphandre for cases like that, if you are interested in contributing or just stay tuned about it.

**Comment by maximeperrault** [comment]
Aww so sad. I'm going to take a look at the discussion. 
I'm very interest at monitoring energy consumption and I would like to make a link between the consumption of cloud provider machines with the type of energy they use in order to make a CO2eq and rank the cloud providers. 

Any idea ? Any plans ?

**Comment by bpetit** [comment]
The thread I indicated is about that, or more exactly to estimate the power consumption only. Once you have the power consumption, you can rely on services like co2signal.com to get the estimated GHG emissions associated.
