### ISSUE TITLE
Support Windows servers - bare metal and virtual hosts

### ISSUE THREAD

**Issue by fradaham** [hubblo-org/scaphandre#74]
## Problem

I have a backend, self developed API-platform, serving billions of requests each year, written in .net Framework and running on old windows 2012 servers (might be we need to migrate to never windows server versions soon). At the same time, we have built a new modern version of our platform, which we run in linux docker containers.

I have two interests. One is of course that I want to be able to generally measure the power consumption for our new platform, to be able to make it as power efficient as possible. Scaphandre seems really promising. I tried it out on a bare metal linux host, and it seems it could cover the docker-case. I will investigate that further.

But the second is that I would like to be able to measure the power consumption of our old platform, running on windows. This to be able to compare to the new platform and hopefully be able to say things like: "If you clients migrate to the new platform, we save X kwh or y tonnes of carbon dioxide - per request!"

To be able to do that, I need something to measure process power consumption on windows, and in my case, the servers are virtual. Scaphandre still doesn't support windows. 

## Solution

I want Scaphandre to be able to measure process power consumption on windows virtual servers.

**Comment by bpetit** [comment]
Hi,

This is something we should go for at some point as there are many windows servers running out there.

I can't say exactly when I could work on that right now as there are some higher priority topics (Warp10, AMD Zen3, ...)
But I hope at least to give it a try and document the challenges to overcome in the following months.

This is great that you asked for it, now it's in the place and if someone wants to give it a try on his own it can be documented here.

**Comment by bpetit** [comment]
In order to provide some materials for the to-be-made documentation, I attach a presentation we prepared to explain how we implemented the support of windows :
[Boavizta - Scaphandre_RAPL_Windows.pdf](https://github.com/hubblo-org/scaphandre/files/8601923/Boavizta.-.Scaphandre_RAPL_Windows.pdf)

**Comment by bpetit** [comment]
We are close to merge this #148 in dev, then in release 0.5.

In the mean time, here is the repo of the driver for reading MSRs on windows : [https://github.com/hubblo-org](https://github.com/hubblo-org/windows-rapl-driver) (there is still documentation and cleaning to do)

A huge thanks to @Vic063 for his tremendous work on this.

**Comment by bpetit** [comment]
About to be released in 0.5 (experimental, no packaging)
