### ISSUE TITLE
Binary link in documentation doesn't work

### ISSUE THREAD

**Issue by maethor** [hubblo-org/scaphandre#80]
The quickstart documentation (https://hubblo-org.github.io/scaphandre/tutorials/quickstart.html) invites to download a binary link (https://github.com/hubblo-org/scaphandre/releases/latest/download/scaphandre-v0.1.1-Ubuntu_20.04-x86_64.gz) which return a 404.

I cannot find a binary for v0.2.0.

Thank you, and good luck in this project.

**Comment by bpetit** [comment]
Hi ! Thanks for noticing, I'll fix that :)

**Comment by bpetit** [comment]
I removed the link for now as we don't have a CI job to build proper binaries for each release. I'll add it back when we get something acceptable on this part.

Thanks for the warning !
