### ISSUE TITLE
Add option to display more than five processes (stdout exporter)

### ISSUE THREAD

**Issue by BasicAcid** [hubblo-org/scaphandre#91]
## Problem

Currently, the stdout exporter only display the first five processes.

## Solution

An interesting feature would be to add an option to the exporter, so that we can view an arbitrary number of processes.

Like ```./scaphandre stdout -p 10```

The difficulty is that making this change require a modification in two files (example with a fixed value):

- One in [src/exporters/stdout.rs](https://github.com/hubblo-org/scaphandre/blob/main/src/exporters/stdout.rs):
    ```rust
    let consumers = self.topology.proc_tracker.get_top_consumers(10);
    ```
    The exporter then display 10 lines, but only the first five are not empty, as scaphandre still send only five of them.

- The second modification in [src/sensors/mod.rs](https://github.com/hubblo-org/scaphandre/blob/main/src/sensors/mod.rs)
    ```rust
    pub fn new() -> Topology {
             Topology {
                 sockets: vec![],
    -            proc_tracker: ProcessTracker::new(5), 
    +            proc_tracker: ProcessTracker::new(10),
                 stat_buffer: vec![],
                 ...
    ```

    Now we really get the ten processes.

For what I understand, it will be required to override the Topology structure inside stdout.rs, but I'm not sure if it is possible, and if it is a good thing (I'm not experienced in Rust).

**Comment by uggla** [comment]
@BasicAcid, I will have a look if I can add this feature. I think it could be also interesting to have a switch to pass a regexp and display the processes that will match it.

**Comment by bpetit** [comment]
Hi !

> The second modification in src/sensors/mod.rs
> 
> pub fn new() -> Topology {
>          Topology {
>              sockets: vec![],
> -            proc_tracker: ProcessTracker::new(5), 
> +            proc_tracker: ProcessTracker::new(10),
>              stat_buffer: vec![],
>              ...

This is not about the number of processes returned in the top consumers list. This is about the number of statistics records we store in the internal "buffer" for each process. You don't need to touch this part to configure the number of process returned by the stdout exporter. This only resides in `src/exporters/stdout.rs` and could look like what I recently proposed on the json exporter:

[https://github.com/hubblo-org/scaphandre/pull/97/files#diff-d4e02f0252f3f8939ffb5643c89bacb8cf4aaeb06ad8f999f02cba1250235335R72](https://github.com/hubblo-org/scaphandre/pull/97/files#diff-d4e02f0252f3f8939ffb5643c89bacb8cf4aaeb06ad8f999f02cba1250235335R72)

and
[https://github.com/hubblo-org/scaphandre/pull/97/files#diff-d4e02f0252f3f8939ffb5643c89bacb8cf4aaeb06ad8f999f02cba1250235335R180](
https://github.com/hubblo-org/scaphandre/pull/97/files#diff-d4e02f0252f3f8939ffb5643c89bacb8cf4aaeb06ad8f999f02cba1250235335R180)

@BasicAcid feel free to look at this code and propose something similar for stdout :)

> I will have a look if I can add this feature. I think it could be also interesting to have a switch to pass a regexp and display the processes that will match it.

@uggla the regexp would be awesome :)

**Comment by uggla** [comment]
Hello fyi, I have worked on this topic. I will open a PR very soon that will allow to choose the number of top consumers to display or to filter an a specific process.
